# Generated by Django 3.2.5 on 2021-08-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Hospital Medical Store', 'Hospital Medical Store'), ('Own Medical Store', 'Own Medical Store'), ('Chain Pharmacy Outlets', 'Chain Pharmacy Outlets')], default=None, max_length=255)),
            ],
            options={
                'verbose_name': 'store_type',
                'verbose_name_plural': 'store_types',
                'db_table': 'store_type',
            },
        ),
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('store_name', models.CharField(default=None, max_length=60)),
                ('username', models.CharField(default=None, max_length=45, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=10)),
                ('store_email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('address_1', models.CharField(default=None, max_length=100)),
                ('address_2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('store_license', models.IntegerField()),
                ('store_registration_no', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('store_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.storetype')),
            ],
            options={
                'verbose_name': 'medical_store',
                'verbose_name_plural': 'medical_stores',
                'db_table': 'medical_store',
                'ordering': ('-id',),
            },
        ),
    ]
