# Generated by Django 3.2.5 on 2021-07-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstore',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
