# Generated by Django 3.2.5 on 2021-08-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_medicalstore_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalstore',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='medicalstore',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='medicalstore',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='medicalstore',
            name='user_permissions',
        ),
    ]
