# Generated by Django 3.2.5 on 2021-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210802_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalstore',
            options={'ordering': ('-id',), 'verbose_name': 'medical_store', 'verbose_name_plural': 'medical_stores'},
        ),
        migrations.AlterField(
            model_name='medicalstore',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
