# Generated by Django 3.2.5 on 2021-08-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicinedetail_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='medicine_details',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='medicine_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
