# Generated by Django 3.2.5 on 2021-08-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('medicines', '0002_alter_medicinedetail_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetail',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='company.company'),
        ),
    ]
