# Generated by Django 3.2.5 on 2021-08-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20210802_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinedetail',
            options={'ordering': ('-id',), 'verbose_name': 'medicine_detail', 'verbose_name_plural': 'medicine_details'},
        ),
    ]
